[package]
name = "systemd2mqtt"
version = "0.1.0"
authors = ["arcnmx"]
edition = "2018"

description = "expose systemd services to mqtt"
keywords = ["systemd", "mqtt"]

homepage = "https://github.com/arcnmx/systemd2mqtt"
repository = "https://github.com/arcnmx/systemd2mqtt"
readme = "README.adoc"
license = "MIT"

[dependencies]
tokio = { version = "^1.0.0", default-features = false, features = ["process", "rt-multi-thread", "time", "macros"] }
anyhow = "^1.0.42"
futures = { version = "^0.3.5", features = ["thread-pool"] }
clap = { version = "^3.1", features = ["derive", "env"] }
env_logger = "^0.9.0"
log = "^0.4.1"
hostname = "^0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
hass-mqtt-discovery = "^0.1"
ctrlc = { version = "^3.1.9", features = ["termination"] }
paho-mqtt = { version = "^0.11.1", default-features = false, features = ["ssl"] }
zbus_systemd = { version = "^0.0.5", features = ["systemd1"] }
